name: Telegram Notification

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *🚀 GitHub Notification*
            
            *📂 Repository:* `${{ github.repository }}`
            *👤 Author:* _${{ github.actor }}_
            
            *📝 Event:* ${{ github.event_name == 'push' && '📥 Push' || '🌳 PR Action' }}
            
            > *Message:*
            > ${{ github.event.head_commit.message || github.event.pull_request.title }}
            
            ---
            *📍 Ref:* `${{ github.ref_name }}`
            *🔗 Action:* [View Changes](https://github.com/${{ github.repository }}/commit/${{ github.sha }})